language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1

before_script:
    - bash -x bin/install_samba.sh
    - composer --dev install
    - mkdir -p build/logs

script:
    - bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
    - bin/coveralls -v
